name: (UPDATE) Model Version

on:
   workflow_dispatch:
    inputs:
      versionNumber:
        description: Updated Version Number.
        required: true

env:
  metadata_path: 'PackagesLocalDirectory'
  
jobs:
  update_model_version:
    runs-on: [self-hosted, Windows, WinStandard]

    steps:

      - name: Cleanup folder
        if: always()
        continue-on-error: true
        shell: powershell
        run:  Remove-Item ${{ github.workspace }}\* -Recurse -Force
         
      - uses: actions/checkout@v3
      
      - uses: ciellos-dev/d365fo-update-model-version@v0.1.3
        with:
         xppSourcePath: ${{ github.workspace }}\${{ env.metadata_path }}
         xppDescriptorSearch: 'Contoso\Descriptor\*.xml'
         xppLayer: "ISV" 
         versionNumber: ${{ github.event.inputs.versionNumber }}
           
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4.0.4
        with: 
          branch: gitmvu
          delete-branch: true
          commit-message: "Update Contoso Model to ${{ github.event.inputs.versionNumber }}"
          title: 'Pushing Version Update ${{ github.event.inputs.versionNumber }} into ${{ github.ref }}'
          labels: automated pr    
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>

      - name: auto-pull-request-merge
        uses: KeisukeYamashita/auto-pull-request-merge@v1.0.6
        with:
            checkStatus: false
            pullRequestNumber: ${{ steps.cpr.outputs.pull-request-number }}
            timeoutSeconds: 500
            token: ${{ secrets.REPO_SCOPED_TOKEN }}
            sha: ${{ steps.cpr.outputs.pull-request-head-sha }}
       
      - name: Delete temp branch
        run: |
           git push origin gitmvu --delete
